### ISSUE TITLE
Windows gets super moany with incbin.c

### ISSUE THREAD

**Issue by IngwiePhoenix** [graphitemaster/incbin#10]
I just tried to compile incbin.c on my 32bit Win7 maschine and it went berserk about missing semicolons and such. Weirdly, renaming the file to `incbin.cpp` (tricking `cl` into C++ mode) fixed the issue. Would be nice if you could look into this.

**Comment by graphitemaster** [comment]
That's odd. I have no Windows environment to test this on. Can you give me the output of the compiler?

**Comment by graphitemaster** [comment]
I converted the code to C90 code. This should fix issues on MSVC

**Comment by IngwiePhoenix** [comment]
I would - but its all German. :)

The updated version works, except for two things:
- `PATH_MAX` is not defined. as far as I know, it is 255 on Windows. But, I cant be sure.
- It complains that `_snprintf` is an undefined symbol. I am looking to find a solution here.

**Comment by IngwiePhoenix** [comment]
I tried to cheat by using `/D snprintf=_snprintf`...but then I got the "Cant open file" error and I have a slight feeling that is due to my...er...fix.

Here is what I found on snprintf: http://stackoverflow.com/questions/3976306/using-snprintf-in-a-cross-platform-application

**Comment by graphitemaster** [comment]
Fixed

**Comment by IngwiePhoenix** [comment]
Works!

I also found news on the `PATH_MAX` macro. A simple ifdef should totally do.

http://bytes.com/topic/c/answers/215365-path_max

So I suggest:

``` c
#ifndef PATH_MAX
#define PATH_MAX 255
#endif
```

**Comment by IngwiePhoenix** [comment]
Turns out its 1024 on my mac. Huh. Who ever needs such long paths though...
