### ISSUE TITLE
Add travis testing

### ISSUE THREAD

**Issue by Habbie** [graphitemaster/incbin#14]
Would you be open to travis-ci.org testing of incbin? I'd be happy to contribute it.

**Comment by IngwiePhoenix** [comment]
I've been using Travis testing in my IceTea project, that also uses Incbin.
Feel free to use that file as a template! :)
https://github.com/IngwiePhoenix/IceTea/blob/master/.travis.yml

It tests across a few compilers and platforms. That is why $TRCXX is used.

2015-12-03 9:17 GMT+01:00 Peter van Dijk notifications@github.com:

**Comment by IngwiePhoenix** [comment]
https://travis-ci.org/IngwiePhoenix/IceTea
Thats the results page.

**Comment by graphitemaster** [comment]
I would be open to testing. But I don't feel like doing all the work to do all that testing :P

**Comment by IngwiePhoenix** [comment]
Well maybe I'll PR a travis file to run incbin on travis for some tiny testing ^^.
