### ISSUE TITLE
GCC auto-depends

### ISSUE THREAD

**Issue by bryceschober** [graphitemaster/incbin#25]
The one flaw in this otherwise perfect-for-the-job tool is that an INCBIN()ed binary doesn't get included in the gcc auto-dependency-file-generation of " -MMD -MP -MF"<depfile>". I wonder if there is some kind of way to fake out gcc/g++ to emit a dependency on the binary file?

**Comment by graphitemaster** [comment]
you could add the incbined binary in your dependeny list manually in make, then add it to a `.PHONY` target, not ideal but does work. Some way of automating this would be nice.

**Comment by bryceschober** [comment]
And if your Makefiles are auto-generated by Eclipse CDT, you're really out of luck. ;-)

**Comment by graphitemaster** [comment]
Was thinking about this problem a bit more. It's actually possible for us to release a tool that parses source files and generates dependency lines like `gcc -MD` does something like the following:
```
file.o: file.c /your/bin/files/here
```

However there's problems with this.

**Comment by bryceschober** [comment]
Problems? Do you mean just having to edit the default-generated dependency files?

I guess this is really a gcc bug, not emitting all of its dependencies, which .incbin files really should be considered...

**Comment by graphitemaster** [comment]
One thing you could do is list all your `INCBIN()` stuff in a single translation unit (e.g `resources.c`, and add that object file to your `Makefile` like):
```
resources.o: FORCE
.PHONY: FORCE
FORCE:
```

This way it's always required to build it, since the file `FORCE` is presumed not to exist, so it is always _created_, so `resources.o` is always out of date w.r.t it, so `resources.o` is always compiled. The `.PHONY` alone won't work though unless it's a static pattern rule. This has more flexibility and can be better integrated into your build process. Really a couple line `Makefile` change. Though if you have a lot of resources you're potentially really pushing it _hard_ here in terms of the amount of data.

**Comment by bryceschober** [comment]
I would actually rather use a custom suffix (like *.incbin.cpp) to enable a
separate pattern rule that added to the dependency file generation by
scanning, which would be logically a lot more cleaner than your proposed
method.

--
Bryce Schober
Senior Software Engineer
Dynon Avionics, Inc. <http://www.dynonavionics.com>

**Comment by graphitemaster** [comment]
That would also work yes, I wad going for a more elegant solution without having to define another pattern rule. There's no real solution to this that incbin can do tho so I'm closing it.

**Comment by jamespharvey20** [comment]
If using `cmake`, adding something like this to `CMakeLists.txt` does the trick:

````
set_property(SOURCE sourceUsingIncbin.cpp
   APPEND PROPERTY OBJECT_DEPENDS "${PROJECT_SOURCE_DIR}/pathTo/binaryFile"
)
````

Could be worth adding a Makefile and `cmake` suggestion to the readme.

**Comment by thomask77** [comment]
I also did not find a way to generate the correct dependencies.

But this looks promising: <https://gcc.gnu.org/onlinedocs/cpp/Pragmas.html#Pragmas>

If you add
```c
_Pragma("GCC dependency \"some_file.bin\"")
```

To the `INCBIN` macro, GCC will output a warning, if `some_file.bin` is newer than the C file.
For example:

```
some_c_file.c:35:16: warning: current file is older than some_file.bin
   35 | _Pragma ("GCC dependency \"some_file.bin\"")
      |                ^~~
```
