### ISSUE TITLE
incbin.c: Visual Studio 2017 missing MAX_PATH

### ISSUE THREAD

**Issue by leximayfield** [graphitemaster/incbin#32]
Pretty simple.  If I compile `incbin.c` using Visual Studio 2017, it complains about a missing `MAX_PATH`.

The following invocation gives me what I need.  It's a little overkill, but it's probably the safest way to ensure `MAX_PATH` exists.

```c
#ifdef _WIN32
#define WIN32_LEAN_AND_MEAN
#include <Windows.h>
#endif
```

**Comment by graphitemaster** [comment]
This has been fixed
