### ISSUE TITLE
What does the incbin.c file do?

### ISSUE THREAD

**Issue by TheRealGlumfish** [graphitemaster/incbin#41]
Thanks for making this. Spent so long trying to find a way to accomplish this task easily and all failed as the ld on Mac OS does not have an option for embedded binaries. I was wondering what the incbin.d file does. Thanks in advance.

**Comment by graphitemaster** [comment]
That file is for MSVC which lacks inline assembler. You can use it as a preprocessing tool to recognize the INCBIN usage in your source files and produce a `data.c` file of all the stuff and include that into your build (for MSVC) for everything else just the header works.

**Comment by asmwarrior** [comment]
> 

Hi, @graphitemaster , can you put the explanation to the home page readme file? I just have the same question, I think the home page should explain about this. Thanks.

For a normal usage, we only need the header file, right?
