### ISSUE TITLE
TinyCC

### ISSUE THREAD

**Issue by PawelA** [graphitemaster/incbin#43]
The readme says it's known to work on TinyCC, but I couldn't get it to work.
TCC's assembler doesn't support the .incbin directive:
https://bellard.org/tcc/tcc-doc.html#Directives
I get the following error:
test.c:3: error: bad expression syntax ["test.txt"]

**Comment by graphitemaster** [comment]
It looks like the official TCC does not supported it, but the community maintained one does.

**Comment by rontrek** [comment]
@graphitemaster where is the git url repo for the community maintained tcc?
