### ISSUE TITLE
INCBIN changes .section for subsequent code

### ISSUE THREAD

**Issue by Habbie** [graphitemaster/incbin#45]
(full background, with some overhead, at https://github.com/PowerDNS/pdns/issues/9835#issuecomment-741748081)

We have this piece of code:
```
INCBIN(api_swagger_yaml, "api-swagger.yaml");
static const string g_api_swagger_yaml{(const char*)gapi_swagger_yamlData, gapi_swagger_yamlSize};
INCBIN(api_swagger_json, "api-swagger.json");
static const string g_api_swagger_json{(const char*)gapi_swagger_jsonData, gapi_swagger_jsonSize};
```

When we compile this with gcc's or clang's Address Sanitizer, it crashes in a string constructor.

Reordering the code like this fixes the problem:
```
INCBIN(api_swagger_yaml, "api-swagger.yaml");
INCBIN(api_swagger_json, "api-swagger.json");
static const string g_api_swagger_yaml{(const char*)gapi_swagger_yamlData, gapi_swagger_yamlSize};
static const string g_api_swagger_json{(const char*)gapi_swagger_jsonData, gapi_swagger_jsonSize};
```

A copy/paste of my understanding of the reason, from the linked ticket:

* INCBIN sets `.section rodata`
* the compiler sets `.bss` for storing the const string
* the next INCBIN call sets `.section rodata` again
* the compiler omits `.bss` for the second const string - presumably because it assumes it is already in BSS

Now the question is - can we add something to the macro to 'restore' the previously active section, or inform the compiler that it needs to repeat its section choice?

**Comment by graphitemaster** [comment]
I think it may be possible to reset to the `.text`.

**Comment by Theldus** [comment]
Maybe [`.pushsection`](https://sourceware.org/binutils/docs/as/PushSection.html)  and [`.popsection`](https://sourceware.org/binutils/docs/as/PopSection.html#PopSection)?, I haven't used these before, so maybe I'm equivocated.

**Comment by hhoffstaette** [comment]
Hi! I encountered this problem when building a C++ program which refused to link with LTO, and found the solution in the GCC bug tracker: [78613](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=78613) and [47071](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=47071).  The fix was indeed simple:
```
diff -up incbin.h~ incbin.h
--- incbin.h~	2018-11-12 09:33:58.000000000 +0100
+++ incbin.h	2021-03-13 17:53:28.552595628 +0100
@@ -216,6 +216,7 @@
             INCBIN_MANGLE INCBIN_STRINGIZE(INCBIN_PREFIX) #NAME "Size:\n" \
                 INCBIN_INT INCBIN_MANGLE INCBIN_STRINGIZE(INCBIN_PREFIX) #NAME "End - " \
                            INCBIN_MANGLE INCBIN_STRINGIZE(INCBIN_PREFIX) #NAME "Data\n" \
+            ".previous" "\n" \
     ); \
     INCBIN_EXTERN(NAME)
```
..and voilà: no more section mismatches during linking :smile:

**Comment by graphitemaster** [comment]
This is a good solution to the problem. I just need to make sure `.previous` works on all the assembler toolchains.

**Comment by graphitemaster** [comment]
It looks like this is already fixed with resetting back to the `.text` section so I sense you just have an out of date copy of incbin maybe?

**Comment by hhoffstaette** [comment]
> It looks like this is already fixed with resetting back to the `.text` section so I sense you just have an out of date copy of incbin maybe?

I used (and patched) the one that came bundled with the source of the package that had problems, and that didn't yet have the fix on master. However said package no loger uses incbin, so .. ¯\\\_(ツ)\_/¯
